@startuml
left to right direction
actor Mobile
actor HMI
rectangle SDL {
  HMI -> (Application Activation)
  (Application Activation) .> (Policy Update) : triggers
  (Application Activation) .> Mobile : HMI Status notification
}
@enduml
