@startuml
note over HMI #ffffff:	Application HMI Type: any\napp_ID successfully registers on SDL\napp_ID in other-than-NULL policies
HMI -> SDL: SDL.ActivateApp (app_ID)
note right: User activates app_ID
SDL ---> HMI: SDL.ActivateApp (SUCCESS)  
SDL -> app_ID: OnHMIStatus (maximum possible HMILevel)
@enduml
