@startuml
left to right direction
actor Mobile
actor HMI
rectangle SDL {
  Mobile -> (Regiter Applicaiton)
  (Regiter Applicaiton) .> (Policy Update) : triggers
  (Regiter Applicaiton) -- HMI
}
@enduml
