@startuml
left to right direction
actor Mobile
actor HMI
rectangle SDL {
  Mobile -- (Activate Applicaiton)
  (Activate Applicaiton) .> (Policy Update) : triggers
  (Activate Applicaiton) -- HMI
}
@enduml
