@startuml
left to right direction
actor Mobile
actor HMI
rectangle SDL {
  Mobile -> (Register Application)
  (Register Application) .> (Policy Update) : triggers
  (Register Application) -- HMI
}
@enduml
