@startuml
note over Application #ffffff: application with appID\nregisters on SDL 
Application -> SDL: \nRegisterAppInterface(params)
note right of SDL #fefdfb:**params** :{\n**application**:{appName,\n**deviceInfo**:{name,id,transportType}\npolicyAppID, appID}\nttsName,vrSynonyms
SDL -> HMI: BC.OnAppRegistered(params, hmi_appID) 

SDL ---> Application: SUCCESS:RegisterAppInterface
note over Application, HMI #ffffff: \nSDL Transfers RPC received from application (usual operating)\n

group On each successful RPC execution
    SDL -> Application: **OnHashChanged(hashID)**
    end
note right of SDL #fefdfb: **RPC**:{AddCommand (Menu+VR)\n-AddSubMenu\n-CreateInteractionChoiceSet\n-SetGlobalProperties\n-SubscribeVehicleData}
note right of SDL #fefdfb:**RPC**:{AddCommand (Menu+VR)\n->DeleteCommand,\n->DeleteSubMenu,\n->DeleteInteractionChoiceSet,\n->ResetGlobalProperties,\n->UnsubscribeButton,\n->UnsubscribeVehicleData}
@enduml
